import Link from 'next/link';
import './globals.scss';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Ecommerce', template: '%s | Ecommerce' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/">Home</Link> <Link href="/products">Products</Link>{' '}
          <Link href="/about">About</Link>
          <br />
        </nav>
        {children}
      </body>
    </html>
  );
}
